require File.expand_path('../boot', __FILE__)

require 'rails/all'

# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)

module Leaderboard
  class Application < Rails::Application

    config.active_record.raise_in_transactional_callbacks = true

    Dir[Rails.root.join('app', 'validations', "*.rb")].each {|l| require l }

    # The URL to host the Ember application from
    config.ember_url = ENV.fetch('EMBER_URL', '/')

    config.assets.enabled = false

    # The URL prefix for Ember assets.
    config.ember_assets_url = ENV.fetch('EMBER_ASSETS_URL', '/')

    config.assets.prefix = '/assets'

    config.assets.paths << "../ember/dist/assets"

    # The URL to the assetMap.json file generated by Ember.
    config.ember_assets_manifest_url = ENV['EMBER_ASSETS_MANIFEST_URL']

    config.api_authorization_token = ENV.fetch('API_AUTHORIZATION_TOKEN', 'notasecret')

    config.middleware.insert_before 0, "Rack::Cors" do
      allow do
        origins '*'
        resource '*', :headers => :any, :methods => [:get, :post, :options]
      end
    end

    config.active_record.raise_in_transactional_callbacks = true
  end
end
