# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17752152b36ec64deb2da49d89b45c62fed59c97de715604c8e59fb12a4af476ab8b262f4000c0dba572c6482a36272a760e08710b034e89065fbfac9c45d1c9

test:
  secret_key_base: c2ec302b0bab3d526c45f8f576f68401393a243c16287cb8c5133a21cc8b08fe599d5aef2d4a351f96cc49d680bd11adb27dae4b837451ab625c476c082e082c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
